# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mars}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-10-16}
  s.default_executable = %q{mars}
  s.description = %q{Disclaimer: this is build for pleasure it is not meant to replace any of the high quality webframeworks like Sinatra and Rails....}
  s.email = %q{mars@jackhq.com}
  s.executables = ["mars"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "lib/coffee_script.rb",
     "lib/mars.rb",
     "lib/mars/css.rb",
     "lib/mars/helpers.rb",
     "lib/mars/images.rb",
     "lib/mars/js.rb",
     "lib/mars_config.rb",
     "lib/mars_mixins.rb",
     "lib/public/favicon.ico",
     "lib/public/index.erb",
     "lib/public/layout.erb",
     "lib/sencha/icon.png",
     "lib/sencha/index.html",
     "lib/sencha/javascripts/coffee-script.js",
     "lib/sencha/javascripts/ext-touch.js",
     "lib/sencha/phone_startup.png",
     "lib/sencha/stylesheets/ext-touch.css",
     "lib/sencha/tablet_startup.png",
     "lib/views/index.haml",
     "lib/views/layout.haml"
  ]
  s.homepage = %q{http://github.com/jackhq/mars}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Microframework built on top of Sinatra}
  s.test_files = [
    "spec/lib/mercury/helpers_spec.rb",
     "spec/lib/mercury/images_spec.rb",
     "spec/lib/mercury_config_spec.rb",
     "spec/mercury_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<faker>, [">= 0"])
      s.add_runtime_dependency(%q<maruku>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<maruku>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<maruku>, [">= 0"])
  end
end

